#!/bin/bash

cd /mnt/
file=$(ls *dmp)

echo "FILE TO BE IMPORTED: "$file

sqlplus -S mirada/mirada@localhost:1521/ORCLCDB @purge_user_mirada.sql

impdp system/system directory=DATA_PUMP_DIR file=$file nologfile=y table_exists_action=replace remap_schema=CV_MEX_MTV:MIRADA EXCLUDE=USER,TABLE:"\"IN ('BMK_BOOKMARK','ACT_ACTIVITY_TAG','ACT_ACTIVITY','PROV_SERVICE_SUBSCRIPTION','YW_CUSTOMER_EPISODE_WATCHED','BILLING_VOD_PURCHASES','HEA_HEALTHCHECK_REPORT','CORE_PROV_AUDIT_LOG','CONT_USER_CONTENT_RATING')\""
impdp system/system directory=DATA_PUMP_DIR file=$file nologfile=y table_exists_action=replace remap_schema=CV_MEX_MTV:MIRADA TABLES=CV_MEX_MTV.BMK_BOOKMARK,CV_MEX_MTV.ACT_ACTIVITY_TAG,CV_MEX_MTV.ACT_ACTIVITY,CV_MEX_MTV.PROV_SERVICE_SUBSCRIPTION,CV_MEX_MTV.YW_CUSTOMER_EPISODE_WATCHED,CV_MEX_MTV.BILLING_VOD_PURCHASES,CV_MEX_MTV.HEA_HEALTHCHECK_REPORT,CV_MEX_MTV.CORE_PROV_AUDIT_LOG,CV_MEX_MTV.CONT_USER_CONTENT_RATING content=METADATA_ONLY