-----------------------
-- Create MIRADA
-----------------------
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER mirada IDENTIFIED BY mirada;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SYNONYM, CREATE TABLESPACE, CREATE SEQUENCE, CREATE TRIGGER, CREATE JOB, CREATE MATERIALIZED VIEW TO mirada;
GRANT ALTER TABLESPACE TO mirada;
GRANT ALTER ANY TABLE, ALTER ANY PROCEDURE, ALTER ANY TRIGGER,  ALTER ANY MATERIALIZED VIEW TO mirada;
GRANT DROP TABLESPACE, DROP ANY TABLE, DROP ANY VIEW, DROP ANY PROCEDURE,DROP ANY SYNONYM, DROP ANY MATERIALIZED VIEW TO mirada;

ALTER USER mirada QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO mirada;

GRANT read, write ON DIRECTORY DATA_PUMP_DIR TO mirada;

-----------------------
-- Create MIRADA_SRM
-----------------------
CREATE USER mirada_srm IDENTIFIED BY mirada_srm;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SYNONYM, CREATE TABLESPACE, CREATE SEQUENCE, CREATE TRIGGER, CREATE JOB, CREATE MATERIALIZED VIEW TO mirada_srm;
GRANT ALTER TABLESPACE TO mirada_srm;
GRANT ALTER ANY TABLE, ALTER ANY PROCEDURE, ALTER ANY TRIGGER,  ALTER ANY MATERIALIZED VIEW TO mirada_srm;
GRANT DROP TABLESPACE, DROP ANY TABLE, DROP ANY VIEW, DROP ANY PROCEDURE,DROP ANY SYNONYM, DROP ANY MATERIALIZED VIEW TO mirada_srm;

ALTER USER mirada_srm QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO mirada_srm;

GRANT read, write ON DIRECTORY DATA_PUMP_DIR TO mirada_srm;


-----------------------
-- Create MIRADA_SM
-----------------------
CREATE USER mirada_sm IDENTIFIED BY mirada_sm;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SYNONYM, CREATE TABLESPACE, CREATE SEQUENCE, CREATE TRIGGER, CREATE JOB, CREATE MATERIALIZED VIEW TO mirada_sm;
GRANT ALTER TABLESPACE TO mirada_sm;
GRANT ALTER ANY TABLE, ALTER ANY PROCEDURE, ALTER ANY TRIGGER,  ALTER ANY MATERIALIZED VIEW TO mirada_sm;
GRANT DROP TABLESPACE, DROP ANY TABLE, DROP ANY VIEW, DROP ANY PROCEDURE,DROP ANY SYNONYM, DROP ANY MATERIALIZED VIEW TO mirada_sm;

ALTER USER mirada_sm QUOTA UNLIMITED ON USERS;
GRANT UNLIMITED TABLESPACE TO mirada_sm;

GRANT read, write ON DIRECTORY DATA_PUMP_DIR TO mirada_sm;