FROM ubuntu:jammy
MAINTAINER Jaime Navarro <jaime.navarro.santapau@gmail.com>

RUN apt-get update 

RUN apt-get -y install apt-utils inetutils-ping traceroute nmap bind-utils bind9-utils dnsutils socat curl
