---
apiVersion: v1
kind: Service
metadata:
  name: proxy-prometheus
  labels:
    app: proxy-prometheus
spec:
  ports:
  - port: 80
    name: proxy
  clusterIP: None
  selector:
    app: proxy-prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-prometheus
  labels:
    app: proxy-prometheus
spec:
  selector:
    matchLabels:
      app: proxy-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy-prometheus
    spec:
      containers:
      - name: proxy-prometheus
        image: jaimenavarro/ubuntu:latest
        imagePullPolicy: Always
        command: ["socat"]
        args: ["-v","TCP4-LISTEN:80,fork,reuseaddr","TCP4:prometheus-server.monitoring.svc.cluster.local:9090"]
        ports:
        - containerPort: 80
          name: proxy
# socat TCP4-LISTEN:9090,fork,reuseaddr TCP4:prometheus.lens-metrics.svc.cluster.local:80