---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  ports:
  - port: 9200
    name: proxy
  clusterIP: None
  selector:
    app: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: jaimenavarro/ubuntu:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          name: proxy
# socat TCP4-LISTEN:9090,fork,reuseaddr TCP4:prometheus.lens-metrics.svc.cluster.local:80